POST http://localhost:3000/users
Content-Type: application/json

{
    "id": 5,
    "nome": "Jekinha",
    "idade": 20,
    "uf": "PB"
}

###
GET http://localhost:3000/users/


###
PATCH http://localhost:3000/users/5
Content-Type: application/json

{
    "nome": "Jessy Mozinha",
    "idade": 27,
    "uf": "RN"
}


###
DELETE http://localhost:3000/users/5
Content-Type: application/json
