POST http://localhost:3000/novoAluno
Content-Type: application/json

{
    "matricula": "123",
    "nome": "Joel de Oliveira Santos",
    "turma": "3º Ano info",
    "email": "teste@gmail.com",
    "genero": "M"
}

###

GET http://localhost:3000/listarAlunos


###

PUT http://localhost:3000/listarAlunos