POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "vídeo teste final",
    "description": "Esse é o vídeo teste final",
    "duration": 200
}

###

GET http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/69c9bf25-f53a-4ffb-8706-950be86f22fe
Content-Type: application/json

{
    "title": "vídeo 02",
    "description": "Esse é o vídeo 02 Editado",
    "duration": 130
}

###

DELETE http://localhost:3333/videos/ab102073-235d-4a6d-ac2e-d403c1adab91


